
DROP TABLE IF EXISTS `LINEUP`;
		
CREATE TABLE `LINEUP` (
  `AREA_ID` BIGINT NOT NULL,
  `NAME` VARCHAR(50),
  PRIMARY KEY (`AREA_ID`)
);

DROP TABLE IF EXISTS `CHANNEL`;
		
CREATE TABLE `CHANNEL` (
  `SOURCE_ID` BIGINT NOT NULL,
  `NAME` VARCHAR(50),
  `CONTENT_ID` BIGINT,
  PRIMARY KEY (`SOURCE_ID`)
);

DROP TABLE IF EXISTS `TV_PACKAGE`;
		
CREATE TABLE `TV_PACKAGE` (
  `OFFERING_ID` BIGINT NOT NULL,
  `NAME` VARCHAR(50),
  PRIMARY KEY (`OFFERING_ID`)
);

DROP TABLE IF EXISTS `PACKAGE_LINEUP`;
		
CREATE TABLE `PACKAGE_LINEUP` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `PACKAGE` BIGINT NOT NULL,
  `LINEUP` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS `PACKAGE_CHANNEL`;
		
CREATE TABLE `PACKAGE_CHANNEL` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `PACKAGE` BIGINT NOT NULL,
  `CHANNEL` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
);


DROP TABLE IF EXISTS `LINEUP_CHANNEL`;
		
CREATE TABLE `LINEUP_CHANNEL` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `LINEUP` BIGINT NOT NULL,
  `CHANNEL` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
);